resources:
- repo: self

phases:
- phase: Linux
  queue:
    name: 'Hosted Ubuntu 1604'
    parallel: 2
    matrix:
      Debug:
        BuildType: Debug
      Release:
        BuildType: Release

  steps:
  - script: |
      sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      sudo apt-get update
      sudo apt-get install -y ninja-build
  - task: CMake@1
    inputs:
      cmakeArgs: '.. -GNinja -DCMAKE_BUILD_TYPE=$(BuildType)'

  - script: |
      ninja
      ctest -j 4 --output-on-failure

    workingDirectory: build
    failOnStderr: true
    displayName: 'Compile & Test'

- phase: macOS
  queue:
    name: 'Hosted macOS'
    parallel: 2
    matrix:
      Debug:
        BuildType: Debug
      Release:
        BuildType: Release

  steps:
  - task: CMake@1
    displayName: 'CMake .. -DCMAKE_BUILD_TYPE=$(BuildType)'
    inputs:
      cmakeArgs: '.. -DCMAKE_BUILD_TYPE=$(BuildType)'

  - script: |
      make -j 4
      ctest -j 4 --output-on-failure

    workingDirectory: build
    failOnStderr: true
    displayName: 'Compile & Test'

